#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libgepub
Version  : 0.6.0
Release  : 3
URL      : https://github.com/GNOME/libgepub/archive/0.6.0.tar.gz
Source0  : https://github.com/GNOME/libgepub/archive/0.6.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.0
Requires: libgepub-data
Requires: libgepub-lib
BuildRequires : glibc-bin
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev
BuildRequires : meson
BuildRequires : ninja
BuildRequires : pkgconfig(libarchive)
BuildRequires : pkgconfig(webkit2gtk-4.0)
BuildRequires : python3

%description
What is libgepub
================
libgepub is a GObject based library for handling and rendering epub
documents.

%package data
Summary: data components for the libgepub package.
Group: Data

%description data
data components for the libgepub package.


%package dev
Summary: dev components for the libgepub package.
Group: Development
Requires: libgepub-lib
Requires: libgepub-data
Provides: libgepub-devel

%description dev
dev components for the libgepub package.


%package lib
Summary: lib components for the libgepub package.
Group: Libraries
Requires: libgepub-data

%description lib
lib components for the libgepub package.


%prep
%setup -q -n libgepub-0.6.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1522119926
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1522119926
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Gepub-0.6.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/libgepub-0.6/gepub-archive.h
/usr/include/libgepub-0.6/gepub-doc.h
/usr/include/libgepub-0.6/gepub-text-chunk.h
/usr/include/libgepub-0.6/gepub-widget.h
/usr/include/libgepub-0.6/gepub.h
/usr/lib64/libgepub-0.6.so
/usr/lib64/pkgconfig/libgepub-0.6.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgepub-0.6.so.0
/usr/lib64/libgepub-0.6.so.0.0.0
